### ISSUE TITLE
Macaulay2 RHEL/CentOS 7 repo

### ISSUE THREAD

**Issue by pieterbowman** [Macaulay2/Macaulay2-web-site#12]
I was just checking to see if there was a CentOS 8 repo yet.  In the process I noticed that Macaulay2 1.15 has been released, but isn't in the repo.  Any chance of updating the packages in the CentOS 7 repo?

Thanks,

Pieter

**Comment by DanGrayson** [comment]
The Scientific Linux version at https://faculty.math.illinois.edu/Macaulay2/Downloads/GNU-Linux/Red%20Hat%20Enterprise,%20CentOS,%20Scientific%20Linux/index.html ought to work for you.  If not, let us know.

**Comment by pieterbowman** [comment]
Dan, Thanks for the reply.  I just realized I submitted this in the  github Macaulay2-web-site issues, sorry.  I also didn't phrase my question very well.  

One question is that the RHEL7/CentOS7/SL7 repo only has M2 1.14, but the RPMs for 1.15 have already been released.  Any chance of getting them into the repo?

The other question is about getting RPMs for RHEL8/CentOS8.  Has any work been done with that?

Thanks again,
Pieter

**Comment by DanGrayson** [comment]
I guess this is a web site issue!   I've just updated the repository, please try it now.

About version 8 -- of RHEL and CentOS, which one is free and earliest with updates?  (I'll install it and make releases from it.)

**Comment by pieterbowman** [comment]
RHEL8 will have updates earlier than CentOS8.  CentOS8 being the free version.  Because of RedHat's high licensing costs for RHEL, we switch to CentOS a few years back.

**Comment by DanGrayson** [comment]
And why is Scientific Linux not out with 8 yet?

**Comment by pieterbowman** [comment]
Last I read the SL folks were calling it quits and switching their efforts to CentOS.  Here's the announcement:
https://listserv.fnal.gov/scripts/wa.exe?A2=SCIENTIFIC-LINUX-ANNOUNCE;11d6001.1904

**Comment by DanGrayson** [comment]
Okay, I'm making a virtual machine with CetnOS8 on it...

**Comment by DanGrayson** [comment]
Centos doesn't include a package for yasm, but I find it at
https://centos.pkgs.org/8/centos-powertools-x86_64/yasm-1.3.0-7.el8.x86_64.rpm.html

How do I add a *.repo file to allow me to install that?

I tried this but it didn't work:

name=power tools
baseurl=https://centos.pkgs.org/8/centos-powertools-x86_64/

**Comment by pieterbowman** [comment]
In /etc/yum.repos.d there should be a file CentOS-PowerTools.repo.  You can enable that repo with:

dnf config-manager --set-enabled PowerTools

**Comment by DanGrayson** [comment]
Thanks!

>

**Comment by DanGrayson** [comment]
@pieterbowman  -- try it now -- I've put a CentOS 8 version in our repository

**Comment by pieterbowman** [comment]
I added the repo to my CentOS 8 test VM and installed Macaulay2 1.15 from the repo.  Worked like a charm.

Thanks
