### ISSUE TITLE
faculty.math.illinois.edu/Macaulay2 and www2.macaulay2.com/Macaulay2 are out of sync

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/Macaulay2-web-site#13]
Example:
http://www2.macaulay2.com/Macaulay2/Downloads/GNU-Linux/Ubuntu/index.html
is older than:
https://faculty.math.illinois.edu/Macaulay2/Downloads/GNU-Linux/Ubuntu/index.html

This should be made automatic, perhaps using Webhooks: https://developer.github.com/webhooks/

**Comment by DanGrayson** [comment]
Thanks for noticing -- I've just pushed.  I should set up a cron job that pushes regularly so I don't have to remember to do.  Since there's more to the website than what's on github, hooks wouldn't be the way to go.

**Comment by mahrud** [comment]
Hooks can trigger a local job the same way that a cron job would. For
other, manual changes that are not on GitHub, you can always trigger it
manually.
