### ISSUE TITLE
Remove the Contributors page

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/Macaulay2-web-site#14]
This page is incomplete, outdated, includes wrong information, and has incorrect emails: https://faculty.math.illinois.edu/Macaulay2/Contributors/

I suggest replacing it with this: https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/_authors_spof_sp__Macaulay2_sppackages.html

**Comment by mahrud** [comment]
Similarly, this page: https://faculty.math.illinois.edu/Macaulay2/Packages/

**Comment by DanGrayson** [comment]
Thanks for noticing.  Done.

**Comment by mahrud** [comment]
That page was linked from the homepage: https://faculty.math.illinois.edu/Macaulay2/
```html
Many <a href="Contributors/">people</a> contribute to <i>Macaulay2</i>
```

**Comment by mahrud** [comment]
Also, I think you should organize the packages by their keywords on that list. Better yet, maybe delete the list and provide a link to https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/_packages_spprovided_spwith_sp__Macaulay2.html

**Comment by DanGrayson** [comment]
Thanks, done.
