### ISSUE TITLE
Online documentation is broken

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/Macaulay2-web-site#24]
All online documentation is broken: [https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/)

Since we just switched to html5, I believe this is the reason:

> Probably because the apache http server on www2 is ignoring the directive `AddType 'application/xhtml+xml' .html` in the file `doc/.htaccess`.  Maybe that subjects the file to more rigorous checking.

_Originally posted by @DanGrayson in https://github.com/Macaulay2/M2/issues/497#issuecomment-737443597_

cc: @d-torrance

**Comment by d-torrance** [comment]
I think it's likely an NGINX configuration issue.  See the discussion at https://github.com/Macaulay2/M2/pull/2850.

**Comment by mahrud** [comment]
@DanGrayson @mikestillman this is still broken.

**Comment by DanGrayson** [comment]
I think it's not worth fixing.  That website is going away soon -- the math department has warned us.

**Comment by mahrud** [comment]
I don't understand. Is it too much effort to have macaulay2.com point to the mirror instead of the broken website?! If you _just_ set up a redirect from www.math.illinois.edu/Macaulay2/ to a working mirror, at least google search results become usable for beginners again!

**Comment by DanGrayson** [comment]
That will be done in due course.

**Comment by mikestillman** [comment]
@DanGrayson What do you mean?  How will that be done?

**Comment by DanGrayson** [comment]
We'll have to do it when the math department removes our primary website.

**Comment by mikestillman** [comment]
If we need to do it, shouldn't we just do it, and then people with current links to the Illinois addresses will start to work again?

**Comment by DanGrayson** [comment]
Okay, you've convinced me.  I'll take care of it tomorrow.

**Comment by mahrud** [comment]
The online documentation is still not working.

**Comment by DanGrayson** [comment]
It's going away Aug 15, so it's not worth fixing it.  I think it's working on the mirror, though.

**Comment by mahrud** [comment]
Do you not own the domain "macaulay2.com"? Currently it is being redirected to a server that does not work and according to you will be decommissioned soon. Who else is going to change macaulay2.com to point somewhere working?

**Comment by DanGrayson** [comment]
> Do you not own the domain "macaulay2.com"? Currently it is being redirected to a server that does not work and according to you will be decommissioned soon. Who else is going to change macaulay2.com to point somewhere working?

Yes, we do own it.  I've redirected it, days ago, but it doesn't seem to have taken effect yet.
