### ISSUE TITLE
Online documentation still on version 1.21

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/Macaulay2-web-site#25]
The website still displays version 1.21:
[http://www2.macaulay2.com/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/](http://www2.macaulay2.com/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/)

**Comment by DanGrayson** [comment]
thanks, fixed.

**Comment by mahrud** [comment]
Now https stopped working.

**Comment by mahrud** [comment]
I can't reopen this, but it shouldn't have been close because this is still pointing to 1.21: http://www2.macaulay2.com/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/
