### ISSUE TITLE
SOS package is not listed on http://www2.macaulay2.com/Macaulay2/Packages/

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/Macaulay2-web-site#4]
yet it is included in 1.13.

**Comment by dimpase** [comment]
also SemidefiniteProgramming is not listed

**Comment by DanGrayson** [comment]
Thanks, all fixed now!

**Comment by dimpase** [comment]
I wanted to send a pull request for this, but a quick look at how the page is built didn't reveal the secret way. :-)

**Comment by DanGrayson** [comment]
Well, perhaps not "secret"! :-)

**Comment by dimpase** [comment]
undocumented :-)
